### ISSUE TITLE
Adapter notifyDataSetChanged() is not working

### ISSUE THREAD

**Issue by alitazami** [erikwt/PullToRefresh-ListView#9] opened 2012-05-06 07:12 UTC
Thanks Eric for the great feature,

I am having a problem with the list adapter it is not rendering the status of my linear layout after the onClickItem, while using the regular listView everything works just fine. Any suggestions to make the adapter work with your pull to refresh listView??
thanks again,

Ali Tazami

**Comment by erikwt** [comment] 2012-07-10 12:16
Could you provide a little more detail? Maybe some example code? I can't seem to reproduce your issue.

**Comment by erikwt** [comment] 2012-08-01 13:20
I'm closing the issue since you didn't respond for a while. If you're still having issues feel free to contact me or open the issue again. Make sure to provide some more info though.

Erik

**Closed as completed by erikwt** 2012-08-01 13:20 UTC

**Comment by lsjwzh** [comment] 2013-10-14 08:19
i have this problem too。
and when the ptr ListView is empty at first。
method “adapter.getCount” will be called frequently。
and then i add an item to adapter and call notifyDataSetChanged, ptrlistview not refresh。

**Comment by lsjwzh** [comment] 2013-10-14 08:33
i got it.
the reason is that i use wrapcontent layout setting.
and i change it to match_parent,it run well.
