### ISSUE TITLE
Problem displaying elements after several "Pull-to-refresh" actions

### ISSUE THREAD

**Issue by hudomju** [erikwt/PullToRefresh-ListView#6] opened 2012-04-20 08:51 UTC
When you do "Pull-to-refresh" several times before the refreshing is finished, you are not able to scroll until the end of the list anymore, so there are some not-displayed or partially-displayed rows

**Comment by erikwt** [comment] 2012-08-01 13:19
Fixed in development branch.

**Closed as completed by erikwt** 2012-08-01 13:19 UTC

**Comment by kimziv** [comment] 2012-10-16 07:53
The issue is really exist...
